### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by niltonmelox** [chrisreedio/filament-breakpoint-badge#9]
### What happened?

Erro when to use the plugin

### How to reproduce the bug

on start plugin

### Package Version

3.0

### PHP Version

8.1.*

### Laravel Version

10.*

### Which operating systems does with happen with?

macOS, Linux

### Notes

Replace:
use ChrisReedIO\FilamentBreakpointBadge\BreakpointBadgePlugin;
by:
use ChrisReedIO\BreakpointBadge\BreakpointBadgePlugin;

**Comment by chrisreedio** [comment]
Thanks for submitting this. 
I had renamed a few things but looks like I missed something. 

I'll get this fixed soon.

**Comment by chrisreedio** [comment]
The README was updated to fix this.

Thanks for reporting and checking out my plugin!

Please star it if you enjoy it ❤️
